### ISSUE TITLE
[BE4] Architecture des pyramides - Ancêtres multiples

### ISSUE THREAD

**Issue by alfredott** [rok4/rok4#3]
Bonjour !

Tout d'abord, je tiens à féliciter votre équipe pour la qualité de BE4, ROK4, et leur documentation. En seulement quelques heures, j'ai réussi à héberger un serveur WMTS basé sur les images satellite (BDORTHO_50cm en opendata) d'un département.

Je n'ai pas vraiment de problème, mais seulement une question à poser (je n'ai pas trouvé de meilleur endroit qu'ici). Imaginons que je souhaite **charger plusieurs départements** (ou en général, plusieurs zones) avec BE4.

**Méthode 1 :**
En premier lieu, j'ai tendance à penser qu'il serait mieux d'utiliser plusieurs pyramides. (Cela permettrait, par exemple, en cas de mise à jour d'un département, de supprimer l'ancienne version d'un département)

Ainsi, je peux agir comme suit : 
- Je charge le département 1 dans une pyramide toute neuve (pyr1)
- Je charge le département 2 dans une nouvelle pyramide (pyr2), avec comme ancêtre, la pyramide pyr1
- ...
- Je charge le département 10 dans une nouvelle pyramide (pyr10) avec comme ancêtre, la pyramide pyr9

Cette méthode impose alors que pyr10 contienne des liens symboliques (symlinks) qui pointent vers de symlinks qui pointent vers des symlinks ... pour enfin pointer vers les tuiles du département 1.

Inconvénients :
- Cela peut peut-être causer des problèmes de performance si on travaille avec de nombreuses zones : pour accéder à une simple image, on passe par des dizaines de symlinks.
- Cela peut aussi être un problème si l'on souhaite supprimer une des pyramides (notamment si les images de ce département sont trop anciennes) : si l'on veut supprimer pyr5, on va alors perdre tous les liens permettant d'accéder à pyr1-2-3-4.

Avantages :
- Chaque département est dans une pyramide différente : c'est plus "propre".

**Méthode 2 :**
Une autre manière pourrait être de charger toutes les images dont je dispose dans une seule pyramide :
- Je charge les départements 1, 2, ... et 10 dans une pyramide toute neuve, et je n'utilise que cette pyramide

Inconvénients :
- Je ne peux pas supprimer un département, si je souhaite faire de la place (par exemple, après en avoir chargé une version plus récente)
- (pas forcément important) Le script de création de la pyramide est très long et la pyramide est très volumineuse

Avantages :
- J'ai toutes les images dans la même pyramide (pas de symlink)

**Méthode 3 :**
Du coup, j'ai pensé à une troisième manière de faire qui (je crois) n'est pas possible dans la version actuelle de BE4.

Dans cette méthode :
- Je charge le département 1 dans une pyramide neuve (pyr1)
- Je charge le département 2 dans une pyramide neuve (pyr2)
- ...
- Je charge le département 10 dans une pyramide neuve (pyr10)
- Enfin, je crée une nouvelle pyramide (pyrGlobale), sans source de données, mais avec 10 pyramides ancêtres : pyr1, pyr2, ..., et pyr10.

Cela nécessiterait que les paramètres liés à la pyramide ancêtre (pyr_name_old, pyr_data_path_old, et pyr_desc_path_old) ne soient pas uniques, mais que l'on puisse en spécifier plusieurs. (Par exemple, sous forme de tableau)

Ainsi, le fichier 'pyramids/descriptors/pyrGlobale.list' commencerait par les lignes suivantes :

-------------------------------
0=/home/moi/testRok4/pyramids/data/PYR1/
1=/home/moi/testRok4/pyramids/data/PYR2/
...
9=/home/moi/testRok4/pyramids/data/PYR10/
\#
-------------------------------

A l'heure actuelle, on ne peut inclure qu'une seule de ces lignes, en plus de la ligne qui correspond à la source de données de la pyramide.

Inconvénients :
- Ce n'est pas encore possible à l'heure actuelle, donc cela nécessite du temps de développement.
- D'autres inconvénients auxquels je n'aurais pas pensé ?

Avantages :
- Toutes les pyramides (sauf pyrGlobale) sont indépendantes les unes des autres. On peut supprimer/ajouter/modifier une pyramide aisément (L'idéal serait de pouvoir ajouter ou supprimer des ancêtres de pyrGlobale, mais dans le pire des cas, on peut regénérer cette pyramide, ce qui a priori ne sera pas trop long, car ce ne sont "que" des symlinks à créer)
- Toutes les images sont accessibles avec un maximum de 1 symlink, donc pas de problème de performance.

**Voilà voilà** ! J'imagine que vous avez beaucoup réfléchi à l'architecture des pyramides. Avez-vous déjà pensé à cette méthode (méthode 3) ? Qu'en pensez-vous ?
Par curiosité, la quelle de ces méthodes est utilisée pour la couche satellite du géoportail ? (Peut-être une autre ?)

Désolé pour le très long message, j'espère qu'il sera utile.
Merci d'avance de vos réponses, et bonne journée !

**Comment by Dolite** [comment]
Bonjour,

Tout d'abord merci pour vos retours positifs.

Nous avons effectivement plusieurs façons de gérer la génération de pyramides, par parties ou non.

Votre méthode 1 est celle que nous utilisons le plus et que nous appelons "_chaînage au fur et à mesure_". Nous avons eu la même reflexion que vous sur les problèmes de "liens en cascade", c'est pourquoi l'outil BE4 va toujours créer des liens vers le fichier d'origine. Ainsi, même après la énième mise à jour, la pyramide N contient des liens symboliques directs vers les version 1, 2... N-1.

Pour des raisons de volume des données, de temps de génération et de mise à jour partielle des données, nous n'utilisons pas la génération "_en une fois_", sauf pour nos données petites/moyennes échelles pour lesquelles tout refaire à chaque fois n'est pas coûteux.

Enfin, votre méthode 3, que nous appelons "_chaînage a posteriori_", est de plus en plus utilisée de notre côté. Nous générons des pyramides indépendentes (souvent par département) et nous utilisons l'outil **JoinCache** (de la suite d'outils BE4) pour créer une pyramide "couverture complète" qui contient principalement des liens vers nos pyramides départementales, et les quelques dalles recalculées aux limites des départements. Cette méthode a un gros avantage sur la méthode 1, c'est qu'elle permet de plus facilement supprimer d'anciens département ou de les corriger. Seule la pyramide en sortie du **JoinCache** est à refaire.

Le référencement de la pyramide ancêtre dans **BE4** peut se faire par des liens physique. Pour faire cela, on ajoute le paramètre `update_mode = hlink` dans la section `pyramide` de la configuration **BE4**.
* Avantage : cela permet de générer par zone mais de pouvoir supprimer au fur et à mesure les anciennes versions. 
* Inconvénient : le lien physique n'est possible qu'au sein d'une même partition

Enfin, il est possible de ne gérer qu'une seule pyramide et de faire des générations "_par injection_" (`update_mode = inject`). Cette dernière va venir modifier les images de la pyramide ancêtre au lieu d'en créer une nouvelle :
* Avantages : si cette pyramide est déjà servie par ROK4, la mise à jour sera diffusée "à chaud", sans avoir à créer une nouvelle couche ou redémarrer le serveur, et pas de liens symboliques
* Inconvénient : on modifie sans rollback possible la pyramide ancêtre

Pour résumer : 
* les outils de génération de pyramide ne font jamais de liens symboliques en cascade (le fichier liste contient justement la liste des fichiers d'origine pour éviter cela)
* les 3 méthodes que vous présentez sont effectivement utilisées par nos services
* il existe également le référencement par lien physique et la mise à jour par injection

N'hésitez pas si vous avez d'autres remarques.

Très bonne soirée.

**Comment by alfredott** [comment]
Bonjour !

Merci pour la réponse rapide ! (La mienne ne l'est pas autant)

Je suis content d'apprendre que l'outil JoinCache existe, c'est exactement ce qu'il me fallait ! Il n'était pas présent dans les tutoriels sur rok4.org, et je n'avais pas assez fouillé la doc. (D'ailleurs, il y a un mauvais lien dans les tutos : "http://www.rok4.org/data/doc/Be4/pyramide/Natural/Html/index.html" au lieu de "http://www.rok4.org/data/doc/latest/Be4/pyramide/Natural/Html/index.html" dans la partie "Les données en entrée" - "Comment la configurer ?" de la page http://www.rok4.org/documentation/comprendre-et-utiliser-be4.)

J'ai fait quelques tests sur l'outil, et apparemment, on peut aussi faire des "JoinCaches de JoinCaches".
Pratique pour segmenter un territoire en groupes de pyramides : par exemple, la France qui contient plusieurs régions qui contiennent elles-mêmes plusieurs départements.

Merci encore pour vos précisions, qui m'ont été très utiles,
Bonne journée !

**Comment by Dolite** [comment]
Merci pour les liens cassés, ils ont été corrigés. C'est vrai qu'il n'y a pas de tutoriel sur l'utilisation de JoinCache. Nous sommes actuellement sur la finalisation d'évolutions importantes du projet (pyramides stockées en mode objet) et une documentation actualisée et plus complète est en cours de réalisation.

Les pyramides ne présentent pas de différence, qu'elles aient été générées par BE4 ou JOINCACHE. De ce fait, on peut indifféremment les utiliser comme sources d'un nouveau JOINCACHE ou BE4. Attention toutefois à ne pas trop découper et empiler les JOINCACHE : cela multiplie le nombre de frontières entre les zones et donc le nombre de dalles à recalculer (le poids total de l'ensemble des pyramides sera supérieur si on fragmente plus). Mais techniquement et d'un point de vue performance de diffusion, cela ne pose aucun problème.

Bonne journée.
