### ISSUE TITLE
"Unrecognized/missing parameters" dans be4.pl

### ISSUE THREAD

**Issue by alfredott** [rok4/rok4#4]
Bonjour,

Après avoir essayé BE4 et ROK4 il y a quelques mois, je souhaite l'installer sur une nouvelle machine. Celle-ci est sur Debian 9, contre Debian 8 pour l'ancienne machine.

Je suis face à un problème lorsque j'essaie d'utiliser be4.pl : le programme crashe après 200ms d'exécution, avec la stack d'erreur suivante :

----------------
\# time be4.pl --conf=proprietes_D072_2016.txt --env=environnement.txt
->          BE4: version [0.25.4]
->          BEGIN
->            OFF : > Configuration (main::main)
->            OFF : >>> Load Properties ... (main::config)
->            OFF : >>> Treat optionnal environment ... (main::config)
->            OFF : > Execution (main::main)
->            OFF : >>> Load a Pyramid ... (main::doIt)
->           INFO : Default value for 'dir_image' : IMAGE (BE4::Pyramid::_init)
->           INFO : Default value for 'dir_nodata' : NODATA (BE4::Pyramid::_init)
->           INFO : Default value for 'dir_mask' : MASK (BE4::Pyramid::_init)
->          Unrecognized/missing parameters: . at /usr/lib/x86_64-linux-gnu/perl5/5.24/Geo/GDAL.pm line 1135.
->                  Geo::GDAL::error("Unrecognized/missing parameters: .") called at /usr/lib/x86_64-linux-gnu/perl5/5.24/Geo/OSR.pm line 109
->                  Geo::OSR::SpatialReference::new("Geo::OSR::SpatialReference") called at /usr/local/bin/../lib/perl5/BE4/TileMatrixSet.pm line 275
->                  BE4::TileMatrixSet::_load(BE4::TileMatrixSet=HASH(0x5585d854f3e0)) called at /usr/local/bin/../lib/perl5/BE4/TileMatrixSet.pm line 187
->                  BE4::TileMatrixSet::new("BE4::TileMatrixSet", "/var/rok4/data/tileMatrixSet/PM.tms") called at /usr/local/bin/../lib/perl5/BE4/Pyramid.pm line 472
->                  BE4::Pyramid::_load(BE4::Pyramid=HASH(0x5585d854f920), HASH(0x5585d8392b60), "./temp_be4_D072_2016") called at /usr/local/bin/../lib/perl5/BE4/Pyramid.pm line 302
->                  BE4::Pyramid::new("BE4::Pyramid", HASH(0x5585d8392b60), "./temp_be4_D072_2016") called at /usr/local/bin/be4.pl line 481
->                  main::doIt() called at /usr/local/bin/be4.pl line 202
->                  main::main() called at /usr/local/bin/be4.pl line 598
->          
->          real    0m0,292s
->          user    0m0,272s
->          sys     0m0,016s

----------------

Je lance la commande sous l'utilisateur root, j'ai bien les bons fichiers de configuration (environnement.txt, proprietes.txt, source.txt), et be4 arrive bien à voir mon fichier de TMS (/var/rok4/data/tileMatrixSet/PM.tms), car quand je change le chemin, il me dit qu'il ne le trouve pas. En revanche, il n'arrive pas à le "charger".
J'ai aussi essayé avec d'autres fichiers .tms, et j'ai le même crash, donc ça n'a pas l'air d'être la faute de ce fichier.

Quand on va voir dans les scripts en question (TileMatrixSet.pm, OSR.pm, GDAL.pm), on voit que le programme crashe en essayant de "charger" le TMS (TileMatrixSet.pm, ligne 187), et plus précisément, dans le paragraphe "Have coordinates to be reversed ?" du fichier TileMatrixSet.pm, au moment d'instancier la "classe" Geo::OSR::SpatialReference, qui est définie dans le fichier OSR.pm.

Auriez-vous une idée du problème ? (Incompatibilité avec Debian 9 ? avec perl v5.24.1 ?...)

Merci d'avance pour votre aide, et bonne journée !

Pièces jointes : les trois scripts les plus en haut de la stack d'erreur.
[GDAL.pm.txt](https://github.com/rok4/rok4/files/1707502/GDAL.pm.txt)
[TileMatrixSet.pm.txt](https://github.com/rok4/rok4/files/1707504/TileMatrixSet.pm.txt)
[OSR.pm.txt](https://github.com/rok4/rok4/files/1707505/OSR.pm.txt)

**Comment by Dolite** [comment]
Bonjour,

Je pense que l'erreur vient d'un changement de version de GDAL. Nous avions déjà remarqué qu'entre GDAL 1.X et GDAL 2.X, la syntaxe pour instancier les objets GDAL en perl avait changé. C'est pour cela que nous avons mis en place une librairie "sur-couche" qui gère ces diffèrentes versions : ProxyGDAL.pm . Cette évolution est présente depuis la version 1.0.0 ([lien vers le commit](https://github.com/rok4/rok4/commit/569568078448e746351a76756aeba0a919c59c04))

Je vous conseille donc d'installer la dernière version, et je pense que le problème devrait disparaître.

En espérant vous avoir aider, je vous souhaite une bonne journée.

**Comment by alfredott** [comment]
Merci !
Je n'avais pas vu que la 0.25.4 n'était pas la dernière, car la "latest release" sur Github est celle-ci.

Avec la 1.1.1, ça a l'air de marcher. En tout cas, on ne crashe plus au début de l'exécution de Be4.
Affaire à suivre

**Comment by alfredott** [comment]
En effet ça fonctionne en utilisant la version 1.1.1 de Rok4, merci encore !
