### ISSUE TITLE
Who to contact for questions ? #notAnActualIssue

### ISSUE THREAD

**Issue by arthurmougin** [rok4/rok4#5]
Hello, 
I consider using rok4 for a professional project, but I would love to get in touch with the team behind this project first.
Who can I contact and how ?
You can close this issue afterward.

Thank you in advance for your help!
Arthur Mougin

en/fr

Bonjour,
J'envisage de travailler avec rok4 pour un projet R&D, mais je souhaiterais d'abord echanger avec l'équipe derrière le projet. 
Qui doit-je contacter et comment ?
Vous pourrez fermer cette issue par la suite.

Merci d'avance pour votre aide!
Arthur Mougin

**Comment by Dolite** [comment]
Bonjour,
Vous pouvez me contacter à l'adresse theo.satabin@ign.fr pour vos questions et voir si ce projet répond à vos besoins.
Bonne journée à vous !
